name: Game_Misc
version: 01.01.03
main: net.mayateck.GameMisc.GameMisc

<nowiki>website: woc.mayateck.net</nowiki>
description: GameData_Misc
author: Wehttam664
preix: Misc

# No Command/Permisison registrys! #
