name: Game_Misc
version: 01.01.03
main: net.mayateck.GameMisc.GameMisc

<nowiki>website: woc.mayateck.net</nowiki>
description: GameData_Misc
author: Wehttam664
preix: Misc

commands:
  announce:
    aliases: ann
    default: false
    usage: /announce [msg]
    permission: misc.announce

permissions:
  misc.*:
    default: false
  misc.announce:
    default: false
