name: Game_Cities
version: 01.00.01
main: net.mayateck.GameCities.GameCities

<nowiki>website: woc.mayateck.net</nowiki>
description: GameData_Organizations
author: Wehttam664
preix: Organizations

commands:
  city:
    description: 'Organizations Core Command'
    aliases: org
    usage: 'Syntax Issue. Try /org help'