name: Game_Organizations
version: 01.03.78
main: net.mayateck.GameCities.GameCities

<nowiki>website: woc.mayateck.net</nowiki>
description: GameData_Organizations
author: Wehttam664
preix: Organizations

commands:
  organization:
    description: 'Organizations Core Command'
    aliases: org
    usage: 'Syntax Issue. Try /org help'